[platformio]
test_dir = tests

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps = 
  jchristensen/DS3232RTC@^2.0.0
  adafruit/RTClib@^1.14.1
build_flags =
  -I nodes/shared

[env:esp32wroom-smoke]
platform = espressif32
board = esp32dev
framework = arduino
test_framework = unity
build_flags =
  -I nodes/shared
test_filter = test_smoke_esp32_wroom
monitor_speed = 115200