#include "ota/mothership_selfupdate.h"
#include "protocol.h"           // NODE_PROTOCOL_VERSION
#include "firmware_identity.h"
#include "firmware_manifest.h"
#include "ota_installer.h"
#include "esp_ota_ops.h"        // esp_ota_get_*_partition, get_partition_description
#include "esp_partition.h"      // esp_partition_find / _next / _get
#include "esp_app_format.h"     // esp_app_desc_t

// ---------------------------------------------------------------------------
// Release verification public key (Ed25519, 32 bytes).
//
// *** PLACEHOLDER — bench/test key from scripts/release_sign.py. ***
// Before any real deployment, replace with the PRODUCTION public key whose
// private half is generated by `release_sign.py keygen` and kept offline.
// ---------------------------------------------------------------------------
static const uint8_t kReleasePubKey[32] = {
  0x29, 0x69, 0xce, 0xb7, 0x91, 0x1a, 0x2c, 0x63, 0xb6, 0x4e, 0x11, 0x52,
  0x70, 0xb9, 0xb7, 0x5c, 0xd8, 0x63, 0x32, 0x2b, 0x12, 0xf3, 0x55, 0xb5,
  0x64, 0xea, 0x47, 0x8f, 0x44, 0xe4, 0x1f, 0x3e };

// Single self-update state (one local upload at a time).
static bool                gManifestReady = false;
static bool                gInstalling    = false;
static OtaInstall          gInstall;
static uint32_t            gExpectedSize  = 0;
static char                gExpectedSha[65];
static char                gTargetVersion[16];
static char                gTargetReleaseId[40];
static FwReason            gLastReason    = FW_NONE;

// TODO: source from persisted NVS once the OTA state store lands. Until then a
// fresh device has no recorded sequence, so anti-downgrade is not yet enforced.
static uint32_t installedReleaseSequence() { return 0; }

FwReason mothershipOtaVerifyManifest(const uint8_t* json, size_t len,
                                     const uint8_t sig[64]) {
  gManifestReady = false;
  gInstalling = false;
  gExpectedSize = 0;

  if (!manifestVerifySignature(json, len, sig, kReleasePubKey)) {
    gLastReason = FW_SIGNATURE_INVALID; return gLastReason;
  }
  Manifest m;
  if (!manifestParse(json, len, m)) { gLastReason = FW_MANIFEST_INVALID; return gLastReason; }

  const ManifestArtifact* art = nullptr;
  FwReason r = manifestCheckCompatibility(m, fwIdentity(NODE_PROTOCOL_VERSION),
                                          installedReleaseSequence(), &art);
  if (r != FW_NONE || !art) { gLastReason = r; return r; }

  gExpectedSize = art->size;
  strlcpy(gExpectedSha, art->sha256, sizeof gExpectedSha);
  strlcpy(gTargetVersion, art->version, sizeof gTargetVersion);
  strlcpy(gTargetReleaseId, m.releaseId, sizeof gTargetReleaseId);
  gManifestReady = true;
  gLastReason = FW_NONE;
  return FW_NONE;
}

FwReason mothershipOtaImageChunk(const uint8_t* data, size_t len) {
  if (!gManifestReady) { gLastReason = FW_MANIFEST_INVALID; return gLastReason; }
  if (!gInstalling) {
    FwReason r = otaInstallBegin(gInstall, gExpectedSize, gExpectedSha);
    if (r != FW_NONE) { gLastReason = r; return r; }
    gInstalling = true;
  }
  FwReason r = otaInstallWrite(gInstall, data, len);
  if (r != FW_NONE) { gInstalling = false; gLastReason = r; }
  return r;
}

FwReason mothershipOtaImageFinish() {
  if (!gInstalling) { gLastReason = FW_IMAGE_INVALID; return gLastReason; }
  gInstalling = false;
  gLastReason = otaInstallFinish(gInstall);
  return gLastReason;
}

void mothershipOtaAbort() {
  if (gInstalling) { otaInstallAbort(gInstall); gInstalling = false; }
  gManifestReady = false;
}

MothershipOtaStatus mothershipOtaGetStatus() {
  MothershipOtaStatus s{};
  s.manifestReady = gManifestReady;
  s.expectedSize  = gExpectedSize;
  s.written       = gInstalling ? gInstall.written : 0;
  s.lastReason    = gLastReason;
  strlcpy(s.targetVersion,  gManifestReady ? gTargetVersion  : "", sizeof s.targetVersion);
  strlcpy(s.targetReleaseId, gManifestReady ? gTargetReleaseId : "", sizeof s.targetReleaseId);
  return s;
}

// Human-readable OTA image state (shared by the running-slot summary field and
// the per-slot table below).
const char* otaImgStateStr(esp_ota_img_states_t st) {
  return (st == ESP_OTA_IMG_PENDING_VERIFY) ? "PENDING_VERIFY" :
         (st == ESP_OTA_IMG_VALID)          ? "CONFIRMED" :
         (st == ESP_OTA_IMG_INVALID)        ? "INVALID" :
         (st == ESP_OTA_IMG_ABORTED)        ? "ABORTED" : "IDLE";
}

// (OtaSlotInfo is declared in the header so fixture tests can build slots[].)

// Enumerate the OTA app slots (app0/app1). The RUNNING slot's identity comes
// from the compiled-in firmware_identity (authoritative). The other slot's
// version is read from its on-flash app descriptor (esp_app_desc_t) — accurate
// for what physically sits there; buildId for the inactive slot is left empty
// until the NVS release store (releaseId) lands. Returns the slot count.
static int readOtaSlots(OtaSlotInfo out[], int maxSlots, const FirmwareIdentity& runId) {
  const esp_partition_t* run  = esp_ota_get_running_partition();
  const esp_partition_t* boot = esp_ota_get_boot_partition();
  int n = 0;
  esp_partition_iterator_t it =
      esp_partition_find(ESP_PARTITION_TYPE_APP, ESP_PARTITION_SUBTYPE_ANY, nullptr);
  while (it != nullptr) {
    const esp_partition_t* p = esp_partition_get(it);
    // Only the OTA app slots — skip factory/test partitions.
    if (p && n < maxSlots &&
        p->subtype >= ESP_PARTITION_SUBTYPE_APP_OTA_0 &&
        p->subtype <= ESP_PARTITION_SUBTYPE_APP_OTA_15) {
      OtaSlotInfo& s = out[n];
      memset(&s, 0, sizeof(s));
      strncpy(s.label, p->label, sizeof(s.label) - 1);
      s.active   = (run  && p->address == run->address);
      s.nextBoot = (boot && p->address == boot->address);

      esp_ota_img_states_t st = ESP_OTA_IMG_UNDEFINED;
      if (esp_ota_get_state_partition(p, &st) != ESP_OK) st = ESP_OTA_IMG_UNDEFINED;
      esp_app_desc_t desc{};
      s.present = (esp_ota_get_partition_description(p, &desc) == ESP_OK);

      if (s.active) {
        strncpy(s.version, runId.semver,  sizeof(s.version) - 1);
        strncpy(s.buildId, runId.buildId, sizeof(s.buildId) - 1);
        s.state = otaImgStateStr(st);
      } else if (s.present) {
        strncpy(s.version, desc.version, sizeof(s.version) - 1);
        s.state = otaImgStateStr(st);
      } else {
        s.state = "EMPTY";
      }
      n++;
    }
    it = esp_partition_next(it);  // releases the current handle
  }
  return n;
}

// Append the slots[] array. Split out so the JSON shape can be exercised with
// fixture data (see tests/test_firmware_slots.cpp) independent of esp_ota.
String mothershipFwSlotsJson(const OtaSlotInfo* slots, int n) {
  String j = "[";
  for (int i = 0; i < n; ++i) {
    if (i) j += ",";
    j += "{\"label\":\"";     j += slots[i].label;
    j += "\",\"version\":\""; j += slots[i].version;
    j += "\",\"buildId\":\""; j += slots[i].buildId;
    j += "\",\"state\":\"";   j += slots[i].state;
    j += "\",\"active\":";    j += slots[i].active   ? "true" : "false";
    j += ",\"nextBoot\":";    j += slots[i].nextBoot ? "true" : "false";
    j += ",\"present\":";     j += slots[i].present  ? "true" : "false";
    j += "}";
  }
  j += "]";
  return j;
}

String mothershipFirmwareStatusJson() {
  FirmwareIdentity id = fwIdentity(NODE_PROTOCOL_VERSION);
  const esp_partition_t* run  = esp_ota_get_running_partition();
  const esp_partition_t* boot = esp_ota_get_boot_partition();
  esp_ota_img_states_t st = ESP_OTA_IMG_UNDEFINED;
  if (run) esp_ota_get_state_partition(run, &st);
  const char* otaState = otaImgStateStr(st);

  OtaSlotInfo slots[4];
  const int nslots = readOtaSlots(slots, 4, id);

  String j = "{\"role\":\"";           j += id.role;
  j += "\",\"version\":\"";           j += id.semver;
  j += "\",\"buildId\":\"";            j += id.buildId;
  j += "\",\"hwTarget\":\"";           j += id.hwTarget;
  j += "\",\"protocolVersion\":";      j += String(id.protocolVersion);
  j += ",\"releaseId\":null";          // populated once the OTA state store lands
  j += ",\"runningSlot\":\"";          j += (run ? run->label : "?");
  j += "\",\"otaState\":\"";           j += otaState;
  j += "\",\"otaReason\":\"";          j += fwReasonStr(gLastReason);
  j += "\",\"lastOtaReason\":\"";      j += fwReasonStr(gLastReason);
  // A/B slot visibility: which slot is active, which boots next, and what each
  // holds. Additive — pre-existing consumers ignore the new keys.
  j += "\",\"activeSlot\":\"";         j += (run  ? run->label  : "?");
  j += "\",\"nextBootSlot\":\"";       j += (boot ? boot->label : "?");
  j += "\",\"slots\":";                j += mothershipFwSlotsJson(slots, nslots);
  j += "}";
  return j;
}

bool mothershipOtaFirstBootCheck() {
  if (!otaIsPendingVerify()) return false;
  esp_err_t err = otaConfirmImage();
  Serial.printf("[OTA] first-boot self-test passed; image confirmed: %s\n",
                esp_err_to_name(err));
  return err == ESP_OK;
}
