#include "ota/mothership_selfupdate.h"
#include "protocol.h"           // NODE_PROTOCOL_VERSION
#include "firmware_identity.h"
#include "firmware_manifest.h"
#include "ota_installer.h"

// ---------------------------------------------------------------------------
// Release verification public key (Ed25519, 32 bytes).
//
// *** PLACEHOLDER — bench/test key from scripts/release_sign.py. ***
// Before any real deployment, replace with the PRODUCTION public key whose
// private half is generated by `release_sign.py keygen` and kept offline.
// ---------------------------------------------------------------------------
static const uint8_t kReleasePubKey[32] = {
  0x29, 0x69, 0xce, 0xb7, 0x91, 0x1a, 0x2c, 0x63, 0xb6, 0x4e, 0x11, 0x52,
  0x70, 0xb9, 0xb7, 0x5c, 0xd8, 0x63, 0x32, 0x2b, 0x12, 0xf3, 0x55, 0xb5,
  0x64, 0xea, 0x47, 0x8f, 0x44, 0xe4, 0x1f, 0x3e };

// Single self-update state (one local upload at a time).
static bool                gManifestReady = false;
static bool                gInstalling    = false;
static OtaInstall          gInstall;
static uint32_t            gExpectedSize  = 0;
static char                gExpectedSha[65];
static char                gTargetVersion[16];
static char                gTargetReleaseId[40];
static FwReason            gLastReason    = FW_NONE;

// TODO: source from persisted NVS once the OTA state store lands. Until then a
// fresh device has no recorded sequence, so anti-downgrade is not yet enforced.
static uint32_t installedReleaseSequence() { return 0; }

FwReason mothershipOtaVerifyManifest(const uint8_t* json, size_t len,
                                     const uint8_t sig[64]) {
  gManifestReady = false;
  gInstalling = false;
  gExpectedSize = 0;

  if (!manifestVerifySignature(json, len, sig, kReleasePubKey)) {
    gLastReason = FW_SIGNATURE_INVALID; return gLastReason;
  }
  Manifest m;
  if (!manifestParse(json, len, m)) { gLastReason = FW_MANIFEST_INVALID; return gLastReason; }

  const ManifestArtifact* art = nullptr;
  FwReason r = manifestCheckCompatibility(m, fwIdentity(NODE_PROTOCOL_VERSION),
                                          installedReleaseSequence(), &art);
  if (r != FW_NONE || !art) { gLastReason = r; return r; }

  gExpectedSize = art->size;
  strlcpy(gExpectedSha, art->sha256, sizeof gExpectedSha);
  strlcpy(gTargetVersion, art->version, sizeof gTargetVersion);
  strlcpy(gTargetReleaseId, m.releaseId, sizeof gTargetReleaseId);
  gManifestReady = true;
  gLastReason = FW_NONE;
  return FW_NONE;
}

FwReason mothershipOtaImageChunk(const uint8_t* data, size_t len) {
  if (!gManifestReady) { gLastReason = FW_MANIFEST_INVALID; return gLastReason; }
  if (!gInstalling) {
    FwReason r = otaInstallBegin(gInstall, gExpectedSize, gExpectedSha);
    if (r != FW_NONE) { gLastReason = r; return r; }
    gInstalling = true;
  }
  FwReason r = otaInstallWrite(gInstall, data, len);
  if (r != FW_NONE) { gInstalling = false; gLastReason = r; }
  return r;
}

FwReason mothershipOtaImageFinish() {
  if (!gInstalling) { gLastReason = FW_IMAGE_INVALID; return gLastReason; }
  gInstalling = false;
  gLastReason = otaInstallFinish(gInstall);
  return gLastReason;
}

void mothershipOtaAbort() {
  if (gInstalling) { otaInstallAbort(gInstall); gInstalling = false; }
  gManifestReady = false;
}

MothershipOtaStatus mothershipOtaGetStatus() {
  MothershipOtaStatus s{};
  s.manifestReady = gManifestReady;
  s.expectedSize  = gExpectedSize;
  s.written       = gInstalling ? gInstall.written : 0;
  s.lastReason    = gLastReason;
  strlcpy(s.targetVersion,  gManifestReady ? gTargetVersion  : "", sizeof s.targetVersion);
  strlcpy(s.targetReleaseId, gManifestReady ? gTargetReleaseId : "", sizeof s.targetReleaseId);
  return s;
}

bool mothershipOtaFirstBootCheck() {
  if (!otaIsPendingVerify()) return false;
  esp_err_t err = otaConfirmImage();
  Serial.printf("[OTA] first-boot self-test passed; image confirmed: %s\n",
                esp_err_to_name(err));
  return err == ESP_OK;
}
