[env:esp32wroom]
platform = espressif32
board = esp32dev
framework = arduino

build_flags =
  -I ../shared
  -D CORE_DEBUG_LEVEL=5
  -D RTC_SDA_PIN=18
  -D RTC_SCL_PIN=19
  -D RTC_INT_PIN=4
  -D ENABLE_POWER_HOLD_CONTROL=1
  -D PWR_HOLD_PIN=23
  -D PWR_HOLD_ACTIVE_HIGH=1
  -D POST_WAKE_WINDOW_MS=1500

monitor_speed = 115200
upload_port = COM3
monitor_port = COM3
upload_speed = 460800
monitor_dtr = 0
monitor_rts = 0

lib_deps =
  adafruit/RTClib@^1.14.1
  adafruit/Adafruit SHT4x Library@^1.0.5
  WiFi
  Wire
  https://github.com/sparkfun/SparkFun_AS7343_Arduino_Library.git
